version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /app
        volumes:
            - ./app:/app
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: nerds!1234
            MYSQL_DATABASE: festivaldb
            MYSQL_USER: prodevs
            MYSQL_PASSWORD: nerds!1234
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: prodevs
            PMA_PASSWORD: nerds!1234
        ports:
            - "8080:80"
        depends_on:
            - mysql
        
volumes:
    db_data: